// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckKasperskyStatus(arg1) {
  return window['go']['main']['App']['CheckKasperskyStatus'](arg1);
}

export function CheckWpsStatus() {
  return window['go']['main']['App']['CheckWpsStatus']();
}

export function ExecuteKasperskyWizard(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ExecuteKasperskyWizard'](arg1, arg2, arg3, arg4);
}

export function ExecuteWpsWizard(arg1) {
  return window['go']['main']['App']['ExecuteWpsWizard'](arg1);
}

export function GetSoftwareModules() {
  return window['go']['main']['App']['GetSoftwareModules']();
}

export function InstallSoftware(arg1) {
  return window['go']['main']['App']['InstallSoftware'](arg1);
}
