// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckKasperskyStatus(arg1:string):Promise<boolean>;

export function CheckWpsStatus():Promise<boolean>;

export function ExecuteKasperskyWizard(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function ExecuteWpsWizard(arg1:string):Promise<void>;

export function GetSoftwareModules():Promise<Array<main.UIModule>>;

export function InstallSoftware(arg1:string):Promise<void>;
